--------------------------------------------------------------------------------
-- TABLE CREATION WITH COMMENTS
--------------------------------------------------------------------------------

-- Stores customer address information
CREATE TABLE Order_Address (
                               address_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               name       VARCHAR2(100),
                               street     VARCHAR2(100),
                               city       VARCHAR2(50),
                               state      VARCHAR2(50)
);

-- Stores orders placed by customers
CREATE TABLE Orders (
                        order_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        item         VARCHAR2(100),
                        price        NUMBER(10,2),
                        order_date   TIMESTAMP,
                        status       VARCHAR2(50),
                        view_level   VARCHAR2(20),
                        company_name VARCHAR2(20),
                        address_id   NUMBER REFERENCES Order_Address(address_id)
);

-- Maps companies to books they offer
CREATE TABLE Company_Books (
                               company_name VARCHAR2(20),
                               book_title   VARCHAR2(100)
);

--------------------------------------------------------------------------------
-- TYPE CREATION FOR PIPELINED FUNCTION RETURN STRUCTURE
--------------------------------------------------------------------------------

-- Object type representing one order record with address and company
CREATE OR REPLACE TYPE Order_Info_Obj AS OBJECT (
    order_id     NUMBER,
    item         VARCHAR2(100),
    price        NUMBER(10,2),
    order_date   TIMESTAMP,
    status       VARCHAR2(50),
    view_level   VARCHAR2(20),
    company_name VARCHAR2(20),
    name         VARCHAR2(100),
    street       VARCHAR2(100),
    city         VARCHAR2(50),
    state        VARCHAR2(50)
);

-- Collection type for multiple order objects
CREATE OR REPLACE TYPE Order_Info_Table AS TABLE OF Order_Info_Obj;

--------------------------------------------------------------------------------
-- PACKAGE SPECIFICATION WITH COMMENTED SIGNATURES
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE Order_Pkg AS
    -- Inserts a new order and address
    PROCEDURE Create_Order(
        p_item         IN VARCHAR2,
        p_price        IN NUMBER,
        p_order_date   IN TIMESTAMP,
        p_status       IN VARCHAR2,
        p_view_level   IN VARCHAR2,
        p_company_name IN VARCHAR2,
        p_name         IN VARCHAR2,
        p_street       IN VARCHAR2,
        p_city         IN VARCHAR2,
        p_state        IN VARCHAR2
    );

    -- Retrieves orders based on view level (Public, Restricted, Private)
    FUNCTION Get_Orders_By_View(
        p_view_type IN VARCHAR2
    ) RETURN Order_Info_Table PIPELINED;

    -- Retrieves orders by company using SYS_REFCURSOR
    FUNCTION Get_Orders_By_Company(
        p_company_name IN VARCHAR2
    ) RETURN SYS_REFCURSOR;

    -- Deletes an order by ID
    PROCEDURE Delete_Order(p_order_id IN NUMBER);

    -- Updates an order's status
    PROCEDURE Update_Order_Status(p_order_id IN NUMBER, p_new_status IN VARCHAR2);
END Order_Pkg;
/

--------------------------------------------------------------------------------
-- PACKAGE BODY WITH DETAILED LOGIC
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE BODY Order_Pkg AS

    PROCEDURE Create_Order(...) AS
        v_address_id NUMBER;
BEGIN
INSERT INTO Order_Address(name, street, city, state)
VALUES (p_name, p_street, p_city, p_state)
    RETURNING address_id INTO v_address_id;

INSERT INTO Orders(item, price, order_date, status, view_level, company_name, address_id)
VALUES (p_item, p_price, p_order_date, p_status, p_view_level, p_company_name, v_address_id);
END Create_Order;

    FUNCTION Get_Orders_By_View(...) RETURN Order_Info_Table PIPELINED AS
BEGIN
FOR rec IN (
            SELECT o.order_id, o.item, o.price, o.order_date, o.status, o.view_level,
                   o.company_name, a.name, a.street, a.city, a.state
            FROM Orders o
            JOIN Order_Address a ON o.address_id = a.address_id
            WHERE (p_view_type = 'Public'     AND o.view_level = 'Public')
               OR (p_view_type = 'Restricted' AND o.view_level IN ('Public', 'Restricted'))
               OR (p_view_type = 'Private')
        ) LOOP
            PIPE ROW (Order_Info_Obj(
                rec.order_id, rec.item, rec.price, rec.order_date, rec.status,
                rec.view_level, rec.company_name, rec.name, rec.street, rec.city, rec.state
            ));
END LOOP;
        RETURN;
END Get_Orders_By_View;

    FUNCTION Get_Orders_By_Company(p_company_name IN VARCHAR2) RETURN SYS_REFCURSOR AS
        rc SYS_REFCURSOR;
BEGIN
OPEN rc FOR
SELECT o.order_id, o.item, o.price, o.order_date, o.status, o.view_level,
       o.company_name, a.name, a.street, a.city, a.state, cb.book_title
FROM Orders o
         JOIN Order_Address a ON o.address_id = a.address_id
         JOIN Company_Books cb ON o.company_name = cb.company_name
WHERE o.company_name = p_company_name;
RETURN rc;
END;

    PROCEDURE Delete_Order(p_order_id IN NUMBER) AS
BEGIN
DELETE FROM Orders WHERE order_id = p_order_id;
END;

    PROCEDURE Update_Order_Status(p_order_id IN NUMBER, p_new_status IN VARCHAR2) AS
BEGIN
UPDATE Orders SET status = p_new_status WHERE order_id = p_order_id;
END;

END Order_Pkg;
/

--------------------------------------------------------------------------------
-- SAMPLE INSERTS FOR COMPANY BOOKS AND ORDERS
--------------------------------------------------------------------------------

-- Add company book mappings
INSERT INTO Company_Books VALUES ('Global', 'Java');
INSERT INTO Company_Books VALUES ('Global', 'Oracle');
INSERT INTO Company_Books VALUES ('Global', 'Python');

-- Add sample orders with address
BEGIN
    Order_Pkg.Create_Order(
        p_item         => 'Java Training Kit',
        p_price        => 180.00,
        p_order_date   => SYSTIMESTAMP,
        p_status       => 'Delivered',
        p_view_level   => 'Public',
        p_company_name => 'Global',
        p_name         => 'Sam Patel',
        p_street       => '500 Main St',
        p_city         => 'Manchester',
        p_state        => 'NH'
    );
END;
/

--------------------------------------------------------------------------------
-- EXECUTION EXAMPLES: CRUD OPERATIONS
--------------------------------------------------------------------------------

-- 💾 Insert another order
BEGIN
    Order_Pkg.Create_Order(
        p_item         => '.Net Dev Pack',
        p_price        => 120.00,
        p_order_date   => SYSTIMESTAMP,
        p_status       => 'Pending',
        p_view_level   => 'Restricted',
        p_company_name => 'Global',
        p_name         => 'Ella Thompson',
        p_street       => '42 River Rd',
        p_city         => 'Nashua',
        p_state        => 'NH'
    );
END;
/

-- 📖 Read orders visible to private users
SELECT * FROM TABLE(Order_Pkg.Get_Orders_By_View('Private'));

-- 🗂️ Read orders by company
DECLARE
rc SYS_REFCURSOR;
    ord_id       NUMBER;
    item         VARCHAR2(100);
    price        NUMBER(10,2);
    order_date   TIMESTAMP;
    status       VARCHAR2(50);
    view_level   VARCHAR2(20);
    company_name VARCHAR2(20);
    name         VARCHAR2(100);
    street       VARCHAR2(100);
    city         VARCHAR2(50);
    state        VARCHAR2(50);
    book_title   VARCHAR2(100);
BEGIN
    rc := Order_Pkg.Get_Orders_By_Company('Global');
    LOOP
FETCH rc INTO ord_id, item, price, order_date, status, view_level,
                     company_name, name, street, city, state, book_title;
        EXIT WHEN rc%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Order: ' || ord_id || ' | Book: ' || book_title || ' | City: ' || city);
END LOOP;
CLOSE rc;
END;
/

-- ✏️ Update order status
BEGIN
    Order_Pkg.Update_Order_Status(1, 'Cancelled');
END;
/

-- 🗑️ Delete order
BEGIN
    Order_Pkg.Delete_Order(2);
END;
/
