--------------------------------------------------------------------------------
-- 🧹 DROP TABLES IF THEY EXIST
--------------------------------------------------------------------------------

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Orders CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Order_Address CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE Company_Books CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

--------------------------------------------------------------------------------
-- 🧹 DROP TYPES IF THEY EXIST
--------------------------------------------------------------------------------

BEGIN
EXECUTE IMMEDIATE 'DROP TYPE Order_Info_Table';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'DROP TYPE Order_Info_Obj';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

--------------------------------------------------------------------------------
-- 🧹 DROP PACKAGE IF EXISTS
--------------------------------------------------------------------------------

BEGIN
EXECUTE IMMEDIATE 'DROP PACKAGE Order_Pkg';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

--------------------------------------------------------------------------------
-- ✅ TABLE CREATION
--------------------------------------------------------------------------------

CREATE TABLE Order_Address (
                               address_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               name       VARCHAR2(100),
                               street     VARCHAR2(100),
                               city       VARCHAR2(50),
                               state      VARCHAR2(50)
);

CREATE TABLE Orders (
                        order_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        item         VARCHAR2(100),
                        price        NUMBER(10,2),
                        order_date   TIMESTAMP,
                        status       VARCHAR2(50),
                        view_level   VARCHAR2(20),
                        company_name VARCHAR2(20),
                        address_id   NUMBER REFERENCES Order_Address(address_id)
);

CREATE TABLE Company_Books (
                               company_name VARCHAR2(20),
                               book_title   VARCHAR2(100)
);

--------------------------------------------------------------------------------
-- ✅ TYPE CREATION
--------------------------------------------------------------------------------

CREATE OR REPLACE TYPE Order_Info_Obj AS OBJECT (
    order_id     NUMBER,
    item         VARCHAR2(100),
    price        NUMBER(10,2),
    order_date   TIMESTAMP,
    status       VARCHAR2(50),
    view_level   VARCHAR2(20),
    company_name VARCHAR2(20),
    name         VARCHAR2(100),
    street       VARCHAR2(100),
    city         VARCHAR2(50),
    state        VARCHAR2(50)
);

CREATE OR REPLACE TYPE Order_Info_Table AS TABLE OF Order_Info_Obj;

--------------------------------------------------------------------------------
-- ✅ PACKAGE SPECIFICATION
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE Order_Pkg AS
    PROCEDURE Create_Order(
        p_item         IN VARCHAR2,
        p_price        IN NUMBER,
        p_order_date   IN TIMESTAMP,
        p_status       IN VARCHAR2,
        p_view_level   IN VARCHAR2,
        p_company_name IN VARCHAR2,
        p_name         IN VARCHAR2,
        p_street       IN VARCHAR2,
        p_city         IN VARCHAR2,
        p_state        IN VARCHAR2
    );

    FUNCTION Get_Orders_By_Access_Level(
        p_company_level IN VARCHAR2
    ) RETURN Order_Info_Table PIPELINED;

    FUNCTION Get_Orders_By_Company(
        p_company_name IN VARCHAR2
    ) RETURN SYS_REFCURSOR;

    PROCEDURE Update_Order_Status(
        p_order_id IN NUMBER,
        p_new_status IN VARCHAR2
    );

    PROCEDURE Delete_Order(
        p_order_id IN NUMBER
    );
END Order_Pkg;
/

--------------------------------------------------------------------------------
-- ✅ PACKAGE BODY WITH ERROR HANDLING
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE BODY Order_Pkg AS

    PROCEDURE Create_Order(p_item         IN VARCHAR2,
    p_price        IN NUMBER,
    p_order_date   IN TIMESTAMP,
    p_status       IN VARCHAR2,
    p_view_level   IN VARCHAR2,
    p_company_name IN VARCHAR2,
    p_name         IN VARCHAR2,
    p_street       IN VARCHAR2,
    p_city         IN VARCHAR2,
    p_state        IN VARCHAR2) AS
        v_address_id NUMBER;
BEGIN
INSERT INTO Order_Address(name, street, city, state)
VALUES (p_name, p_street, p_city, p_state)
    RETURNING address_id INTO v_address_id;

INSERT INTO Orders(item, price, order_date, status, view_level, company_name, address_id)
VALUES (p_item, p_price, p_order_date, p_status, p_view_level, p_company_name, v_address_id);

DBMS_OUTPUT.PUT_LINE('✅ Order created for: ' || p_name);
EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('❌ Create_Order failed: ' || SQLERRM);
            RAISE;
END Create_Order;

    FUNCTION Get_Orders_By_Access_Level(p_company_level IN VARCHAR2)
    RETURN Order_Info_Table PIPELINED
    AS
        v_visible_levels SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST();
BEGIN
CASE UPPER(p_company_level)
            WHEN 'GLOBAL' THEN
                v_visible_levels := SYS.ODCIVARCHAR2LIST('Global');
WHEN 'NATIONAL' THEN
                v_visible_levels := SYS.ODCIVARCHAR2LIST('National', 'Global');
WHEN 'REGIONAL' THEN
                v_visible_levels := SYS.ODCIVARCHAR2LIST('Regional', 'National', 'Global');
WHEN 'LOCAL' THEN
                v_visible_levels := SYS.ODCIVARCHAR2LIST('Local', 'Regional', 'National', 'Global');
ELSE
                RAISE_APPLICATION_ERROR(-20001, 'Invalid company level: ' || p_company_level);
END CASE;

FOR rec IN (
            SELECT o.order_id, o.item, o.price, o.order_date, o.status, o.view_level,
                   o.company_name, a.name, a.street, a.city, a.state
            FROM Orders o
            JOIN Order_Address a ON o.address_id = a.address_id
            WHERE o.company_name IN (SELECT COLUMN_VALUE FROM TABLE(v_visible_levels))
        ) LOOP
            PIPE ROW (Order_Info_Obj(
                rec.order_id, rec.item, rec.price, rec.order_date, rec.status,
                rec.view_level, rec.company_name, rec.name, rec.street, rec.city, rec.state
            ));
END LOOP;

        RETURN;
EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('❌ Error in Get_Orders_By_Access_Level: ' || SQLERRM);
            RAISE;
END;

    FUNCTION Get_Orders_By_Company(p_company_name IN VARCHAR2)
    RETURN SYS_REFCURSOR
    AS
        rc SYS_REFCURSOR;
BEGIN
OPEN rc FOR
SELECT o.order_id, o.item, o.price, o.order_date, o.status, o.view_level,
       o.company_name, a.name, a.street, a.city, a.state, cb.book_title
FROM Orders o
         JOIN Order_Address a ON o.address_id = a.address_id
         JOIN Company_Books cb ON o.company_name = cb.company_name
WHERE o.company_name = p_company_name;

RETURN rc;
EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('❌ Error in Get_Orders_By_Company: ' || SQLERRM);
            RAISE;
END;

    PROCEDURE Update_Order_Status(p_order_id IN NUMBER, p_new_status IN VARCHAR2) AS
BEGIN
UPDATE Orders SET status = p_new_status WHERE order_id = p_order_id;

IF SQL%ROWCOUNT = 0 THEN
            DBMS_OUTPUT.PUT_LINE('⚠ No order found with ID: ' || p_order_id);
ELSE
            DBMS_OUTPUT.PUT_LINE('✅ Status updated for Order ' || p_order_id);
END IF;
EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('❌ Error in Update_Order_Status: ' || SQLERRM);
            RAISE;
END;

    PROCEDURE Delete_Order(p_order_id IN NUMBER) AS
BEGIN
DELETE FROM Orders WHERE order_id = p_order_id;

IF SQL%ROWCOUNT = 0 THEN
            DBMS_OUTPUT.PUT_LINE('⚠ No order to delete with ID: ' || p_order_id);
ELSE
            DBMS_OUTPUT.PUT_LINE('✅ Order ' || p_order_id || ' deleted.');
END IF;
EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('❌ Error in Delete_Order: ' || SQLERRM);
            RAISE;
END;

END Order_Pkg;
/

--------------------------------------------------------------------------------
-- 📚 SAMPLE DATA INSERTS
--------------------------------------------------------------------------------

-- Company books
INSERT INTO Company_Books VALUES ('Global', 'Java');
INSERT INTO Company_Books VALUES ('National', 'Python');

-- Sample orders
BEGIN
    Order_Pkg.Create_Order(
        'Java Dev Kit', 180, SYSTIMESTAMP, 'Delivered', 'Public', 'Global',
        'Alice Gray', '1 Elm Street', 'Boston', 'MA'
    );

    Order_Pkg.Create_Order(
        'Python Starter', 160, SYSTIMESTAMP, 'Pending', 'Restricted', 'National',
        'Bob Taylor', '22 Data Lane', 'Manchester', 'NH'
    );
END;
/

--------------------------------------------------------------------------------
-- 🚀 EXECUTION SAMPLES
--------------------------------------------------------------------------------

-- View visible orders for a Local company
SELECT * FROM TABLE(Order_Pkg.Get_Orders_By_Access_Level('Local'));

-- View books and order details for Global company
DECLARE
rc SYS_REFCURSOR;
    ord_id       NUMBER;
    item         VARCHAR2(100);
    price        NUMBER(10,2);
    order_date   TIMESTAMP;
    status       VARCHAR2(50);
    view_level   VARCHAR2(20);
    company_name VARCHAR2(20);
    name         VARCHAR2(100);
    street       VARCHAR2(100);
    city         VARCHAR2(50);
    state        VARCHAR2(50);
    book_title   VARCHAR2(100);
BEGIN
    rc := Order_Pkg.Get_Orders_By_Company('Global');
    LOOP
FETCH rc INTO ord_id, item, price, order_date, status, view_level,
                     company_name, name, street, city, state, book_title;
        EXIT WHEN rc%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Order ID: ' || ord_id || ', Book: ' || book_title || ', Customer: ' || name);
END LOOP;
CLOSE rc;
END;
/

-- Update an order status
BEGIN
    Order_Pkg.Update_Order_Status(1, 'Shipped');
END;
/

-- Delete an order
BEGIN
    Order_Pkg.Delete_Order(2);
END;
/


--- New operation ---
BEGIN
    Order_Pkg.Create_Order(
        p_item         => 'Spring Boot Mastery',
        p_price        => 190.00,
        p_order_date   => SYSTIMESTAMP,
        p_status       => 'Processing',
        p_view_level   => 'Restricted',
        p_company_name => 'Global',
        p_name         => 'Nina Roberts',
        p_street       => '88 Innovation Blvd',
        p_city         => 'Portsmouth',
        p_state        => 'NH'
    );
END;
/

--- Read operation ---
--2. Read Operation — View Orders by Company Access Level

SELECT *
FROM TABLE(Order_Pkg.Get_Orders_By_Access_Level('Local'));


-- 3. Read Operation — View Orders and Book Titles for Specific Company --

DECLARE
rc SYS_REFCURSOR;
    ord_id       NUMBER;
    item         VARCHAR2(100);
    price        NUMBER(10,2);
    order_date   TIMESTAMP;
    status       VARCHAR2(50);
    view_level   VARCHAR2(20);
    company_name VARCHAR2(20);
    name         VARCHAR2(100);
    street       VARCHAR2(100);
    city         VARCHAR2(50);
    state        VARCHAR2(50);
    book_title   VARCHAR2(100);
BEGIN
    rc := Order_Pkg.Get_Orders_By_Company('Global');
    LOOP
FETCH rc INTO ord_id, item, price, order_date, status, view_level,
                     company_name, name, street, city, state, book_title;
        EXIT WHEN rc%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(
            'Order: ' || ord_id ||
            ', Book: ' || book_title ||
            ', Customer: ' || name ||
            ', City: ' || city
        );
END LOOP;
CLOSE rc;
END;
/

-- 4. Update Operation — Change Order Status --
BEGIN
    Order_Pkg.Update_Order_Status(1, 'Shipped');  -- Replace 1 with a valid order_id
END;
/


-- 5. Delete Operation — Remove an Order --
BEGIN
    Order_Pkg.Delete_Order(244);  -- Replace 2 with a valid order_id to delete
END;
/

