--------------------------------------------------------------------------------
-- 💾 TABLE DEFINITIONS WITH COMMENTS
--------------------------------------------------------------------------------

-- Stores customer address information
CREATE TABLE Order_Address (
                               address_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               name       VARCHAR2(100),
                               street     VARCHAR2(100),
                               city       VARCHAR2(50),
                               state      VARCHAR2(50)
);

-- Stores customer orders
CREATE TABLE Orders (
                        order_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        item         VARCHAR2(100),
                        price        NUMBER(10,2),
                        order_date   TIMESTAMP,
                        status       VARCHAR2(50),         -- e.g. 'Delivered'
                        view_level   VARCHAR2(20),         -- Optional field
                        company_name VARCHAR2(20),         -- e.g. 'Global', 'National', etc.
                        address_id   NUMBER REFERENCES Order_Address(address_id)
);

-- Maps companies to books they offer
CREATE TABLE Company_Books (
                               company_name VARCHAR2(20),
                               book_title   VARCHAR2(100)
);

--------------------------------------------------------------------------------
-- 📦 TYPE DEFINITIONS FOR PIPELINED FUNCTIONS
--------------------------------------------------------------------------------

-- Object representing one enriched order record
CREATE OR REPLACE TYPE Order_Info_Obj AS OBJECT (
    order_id     NUMBER,
    item         VARCHAR2(100),
    price        NUMBER(10,2),
    order_date   TIMESTAMP,
    status       VARCHAR2(50),
    view_level   VARCHAR2(20),
    company_name VARCHAR2(20),
    name         VARCHAR2(100),
    street       VARCHAR2(100),
    city         VARCHAR2(50),
    state        VARCHAR2(50)
);

-- Collection of enriched order records
CREATE OR REPLACE TYPE Order_Info_Table AS TABLE OF Order_Info_Obj;

--------------------------------------------------------------------------------
-- 📦 PACKAGE SPECIFICATION: Order_Pkg
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE Order_Pkg AS
    PROCEDURE Create_Order(
        p_item         IN VARCHAR2,
        p_price        IN NUMBER,
        p_order_date   IN TIMESTAMP,
        p_status       IN VARCHAR2,
        p_view_level   IN VARCHAR2,
        p_company_name IN VARCHAR2,
        p_name         IN VARCHAR2,
        p_street       IN VARCHAR2,
        p_city         IN VARCHAR2,
        p_state        IN VARCHAR2
    );

    FUNCTION Get_Orders_By_Access_Level(
        p_company_level IN VARCHAR2
    ) RETURN Order_Info_Table PIPELINED;

    FUNCTION Get_Orders_By_Company(
        p_company_name IN VARCHAR2
    ) RETURN SYS_REFCURSOR;

    PROCEDURE Update_Order_Status(
        p_order_id IN NUMBER,
        p_new_status IN VARCHAR2
    );

    PROCEDURE Delete_Order(
        p_order_id IN NUMBER
    );
END Order_Pkg;
/

--------------------------------------------------------------------------------
-- 📦 PACKAGE BODY IMPLEMENTATION
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE BODY Order_Pkg AS

    PROCEDURE Create_Order(
        p_item         IN VARCHAR2,
        p_price        IN NUMBER,
        p_order_date   IN TIMESTAMP,
        p_status       IN VARCHAR2,
        p_view_level   IN VARCHAR2,
        p_company_name IN VARCHAR2,
        p_name         IN VARCHAR2,
        p_street       IN VARCHAR2,
        p_city         IN VARCHAR2,
        p_state        IN VARCHAR2
    ) AS
        v_address_id NUMBER;
BEGIN
INSERT INTO Order_Address(name, street, city, state)
VALUES (p_name, p_street, p_city, p_state)
    RETURNING address_id INTO v_address_id;

INSERT INTO Orders(item, price, order_date, status, view_level, company_name, address_id)
VALUES (p_item, p_price, p_order_date, p_status, p_view_level, p_company_name, v_address_id);
END Create_Order;

    FUNCTION Get_Orders_By_Access_Level(p_company_level IN VARCHAR2)
    RETURN Order_Info_Table PIPELINED
    AS
        v_visible_levels SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST();
BEGIN
CASE UPPER(p_company_level)
            WHEN 'GLOBAL' THEN
                v_visible_levels := SYS.ODCIVARCHAR2LIST('Global');
WHEN 'NATIONAL' THEN
                v_visible_levels := SYS.ODCIVARCHAR2LIST('National', 'Global');
WHEN 'REGIONAL' THEN
                v_visible_levels := SYS.ODCIVARCHAR2LIST('Regional', 'National', 'Global');
WHEN 'LOCAL' THEN
                v_visible_levels := SYS.ODCIVARCHAR2LIST('Local', 'Regional', 'National', 'Global');
ELSE
                RAISE_APPLICATION_ERROR(-20001, 'Unknown company level: ' || p_company_level);
END CASE;

FOR rec IN (
            SELECT o.order_id, o.item, o.price, o.order_date, o.status, o.view_level,
                   o.company_name,
                   a.name, a.street, a.city, a.state
            FROM Orders o
            JOIN Order_Address a ON o.address_id = a.address_id
            WHERE o.company_name IN (SELECT COLUMN_VALUE FROM TABLE(v_visible_levels))
        ) LOOP
            PIPE ROW (Order_Info_Obj(
                rec.order_id, rec.item, rec.price, rec.order_date, rec.status,
                rec.view_level, rec.company_name, rec.name, rec.street, rec.city, rec.state
            ));
END LOOP;

        RETURN;
END;

    FUNCTION Get_Orders_By_Company(p_company_name IN VARCHAR2)
    RETURN SYS_REFCURSOR
    AS
        rc SYS_REFCURSOR;
BEGIN
OPEN rc FOR
SELECT o.order_id, o.item, o.price, o.order_date, o.status, o.view_level,
       o.company_name, a.name, a.street, a.city, a.state, cb.book_title
FROM Orders o
         JOIN Order_Address a ON o.address_id = a.address_id
         JOIN Company_Books cb ON o.company_name = cb.company_name
WHERE o.company_name = p_company_name;
RETURN rc;
END;

    PROCEDURE Update_Order_Status(p_order_id IN NUMBER, p_new_status IN VARCHAR2) AS
BEGIN
UPDATE Orders SET status = p_new_status WHERE order_id = p_order_id;
END;

    PROCEDURE Delete_Order(p_order_id IN NUMBER) AS
BEGIN
DELETE FROM Orders WHERE order_id = p_order_id;
END;

END Order_Pkg;
/

--------------------------------------------------------------------------------
-- 📚 SAMPLE DATA INSERTS
--------------------------------------------------------------------------------

-- Add book titles for various company levels
INSERT INTO Company_Books VALUES ('Global', 'Java');
INSERT INTO Company_Books VALUES ('Global', 'Oracle');
INSERT INTO Company_Books VALUES ('National', 'Python');
INSERT INTO Company_Books VALUES ('Regional', 'PL/SQL');
INSERT INTO Company_Books VALUES ('Local', 'JavaScript');

-- Add sample orders
BEGIN
    Order_Pkg.Create_Order(
        p_item         => 'Java Dev Kit',
        p_price        => 180.00,
        p_order_date   => SYSTIMESTAMP,
        p_status       => 'Delivered',
        p_view_level   => 'Public',
        p_company_name => 'Global',
        p_name         => 'Emma Gray',
        p_street       => '1 Elm Street',
        p_city         => 'Boston',
        p_state        => 'MA'
    );

    Order_Pkg.Create_Order(
        p_item         => 'Python Essentials',
        p_price        => 160.00,
        p_order_date   => SYSTIMESTAMP,
        p_status       => 'Processing',
        p_view_level   => 'Restricted',
        p_company_name => 'National',
        p_name         => 'Lucas Rivera',
        p_street       => '22 Maple Ave',
        p_city         => 'Manchester',
        p_state        => 'NH'
    );
END;
/

--------------------------------------------------------------------------------
-- 🚀 QUERY EXECUTION SAMPLES
--------------------------------------------------------------------------------

-- View orders accessible to a Regional company
SELECT * FROM TABLE(Order_Pkg.Get_Orders_By_Access_Level('Regional'));

-- View orders accessible to a Local company
SELECT * FROM TABLE(Order_Pkg.Get_Orders_By_Access_Level('Local'));

-- View orders for 'Global' via SYS_REFCURSOR (inside PL/SQL block)
DECLARE
rc SYS_REFCURSOR;
    ord_id       NUMBER;
    item         VARCHAR2(100);
    price        NUMBER(10,2);
    order_date   TIMESTAMP;
    status       VARCHAR2(50);
    view_level   VARCHAR2(20);
    company_name VARCHAR2(20);
    name         VARCHAR2(100);
    street       VARCHAR2(100);
    city         VARCHAR2(50);
    state        VARCHAR2(50);
    book_title   VARCHAR2(100);
BEGIN
    rc := Order_Pkg.Get_Orders_By_Company('Global');
    LOOP
FETCH rc INTO ord_id, item, price, order_date, status, view_level,
                     company_name, name, street, city, state, book_title;
        EXIT WHEN rc%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('Order: ' || ord_id || ', Book: ' || book_title || ', City: ' || city);
END LOOP;
