-- 🔄 Drop student table if exists
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE student';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- 🔄 Drop audit log table if exists
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE student_audit_log';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- 🧾 Create student table
CREATE TABLE student (
                         student_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         first_name     VARCHAR2(100),
                         last_name      VARCHAR2(100),
                         username       VARCHAR2(100),
                         email          VARCHAR2(150),
                         address_blob   BLOB,
                         gift_blob      BLOB,
                         gift_date      TIMESTAMP,
                         created_at     TIMESTAMP DEFAULT SYSDATE,
                         updated_at     TIMESTAMP
);


-- 🧾 Create audit log table
CREATE TABLE student_audit_log (
                                   log_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                   student_id    NUMBER,
                                   action        VARCHAR2(50),
                                   description   VARCHAR2(500),
                                   log_time      TIMESTAMP DEFAULT SYSTIMESTAMP
);


-- 🔄 Drop package if it exists
BEGIN
EXECUTE IMMEDIATE 'DROP PACKAGE student_pkg';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -4043 THEN RAISE; END IF;
END;
/

-- 📘 Package specification
CREATE OR REPLACE PACKAGE student_pkg AS
    PROCEDURE create_student (
        p_first_name    IN VARCHAR2,
        p_last_name     IN VARCHAR2,
        p_username      IN VARCHAR2,
        p_email         IN VARCHAR2,
        p_address_json  IN CLOB,
        p_gift_json     IN CLOB,
        p_gift_date     IN TIMESTAMP,
        p_student_id    OUT NUMBER
    );

    PROCEDURE update_student (
        p_student_id    IN NUMBER,
        p_first_name    IN VARCHAR2,
        p_last_name     IN VARCHAR2,
        p_username      IN VARCHAR2,
        p_email         IN VARCHAR2,
        p_address_json  IN CLOB,
        p_gift_json     IN CLOB,
        p_gift_date     IN TIMESTAMP
    );

    PROCEDURE get_student (
        p_student_id IN NUMBER,
        p_result     OUT SYS_REFCURSOR
    );

    PROCEDURE delete_student (
        p_student_id IN NUMBER
    );
END student_pkg;
/
-- body

CREATE OR REPLACE PACKAGE BODY student_pkg AS

    PROCEDURE log_action(p_id NUMBER, p_action VARCHAR2, p_description VARCHAR2) IS
BEGIN
INSERT INTO student_audit_log(student_id, action, description)
VALUES (p_id, p_action, p_description);
END;

    PROCEDURE create_student (
        p_first_name    IN VARCHAR2,
        p_last_name     IN VARCHAR2,
        p_username      IN VARCHAR2,
        p_email         IN VARCHAR2,
        p_address_json  IN CLOB,
        p_gift_json     IN CLOB,
        p_gift_date     IN TIMESTAMP,
        p_student_id    OUT NUMBER
    )
IS
        v_address_blob  BLOB;
        v_gift_blob     BLOB;
        v_gift_status   VARCHAR2(50);
        v_gift_date     TIMESTAMP;
BEGIN
        -- Validation
        IF p_first_name IS NULL OR TRIM(p_first_name) = '' THEN
            RAISE_APPLICATION_ERROR(-20001, 'First name is required.');
        ELSIF p_last_name IS NULL OR TRIM(p_last_name) = '' THEN
            RAISE_APPLICATION_ERROR(-20002, 'Last name is required.');
        ELSIF p_username IS NULL OR TRIM(p_username) = '' THEN
            RAISE_APPLICATION_ERROR(-20003, 'Username is required.');
        ELSIF p_email IS NULL OR TRIM(p_email) = '' THEN
            RAISE_APPLICATION_ERROR(-20004, 'Email is required.');
        ELSIF NOT REGEXP_LIKE(p_email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
            RAISE_APPLICATION_ERROR(-20005, 'Email format is invalid.');
END IF;

        v_address_blob := CASE
            WHEN p_address_json IS NOT NULL THEN
                UTL_RAW.CAST_TO_RAW(SUBSTR(p_address_json, 1, 4000))
            ELSE NULL
END;

        v_gift_blob := CASE
            WHEN p_gift_json IS NOT NULL THEN
                UTL_RAW.CAST_TO_RAW(SUBSTR(p_gift_json, 1, 4000))
            ELSE NULL
END;

        v_gift_status := JSON_VALUE(p_gift_json, '$.status');

        IF v_gift_status = 'Delivered' THEN
            v_gift_date := p_gift_date;
        ELSIF v_gift_status IS NOT NULL AND v_gift_status <> 'Delivered' THEN
            IF p_gift_date IS NOT NULL THEN
                RAISE_APPLICATION_ERROR(-20006, 'giftDate should not be passed when status is not Delivered.');
END IF;
            v_gift_date := NULL;
ELSE
            v_gift_date := NULL;
END IF;

INSERT INTO student (
    first_name, last_name, username, email,
    address_blob, gift_blob, gift_date, created_at
)
VALUES (
           p_first_name, p_last_name, p_username, p_email,
           v_address_blob, v_gift_blob, v_gift_date, SYSTIMESTAMP
       )
    RETURNING student_id INTO p_student_id;

log_action(p_student_id, 'CREATE', 'Student created');
END;

    PROCEDURE update_student (
        p_student_id    IN NUMBER,
        p_first_name    IN VARCHAR2,
        p_last_name     IN VARCHAR2,
        p_username      IN VARCHAR2,
        p_email         IN VARCHAR2,
        p_address_json  IN CLOB,
        p_gift_json     IN CLOB,
        p_gift_date     IN TIMESTAMP
    )
IS
        v_address_blob  BLOB;
        v_gift_blob     BLOB;
        v_gift_status   VARCHAR2(50);
        v_gift_date     TIMESTAMP;
BEGIN
        IF p_student_id IS NULL THEN
            RAISE_APPLICATION_ERROR(-20010, 'Student ID is required.');
END IF;

        -- Same validation + conversion logic as create
        v_address_blob := CASE
            WHEN p_address_json IS NOT NULL THEN
                UTL_RAW.CAST_TO_RAW(SUBSTR(p_address_json, 1, 4000))
            ELSE NULL
END;

        v_gift_blob := CASE
            WHEN p_gift_json IS NOT NULL THEN
                UTL_RAW.CAST_TO_RAW(SUBSTR(p_gift_json, 1, 4000))
            ELSE NULL
END;

        v_gift_status := JSON_VALUE(p_gift_json, '$.status');

        IF v_gift_status = 'Delivered' THEN
            v_gift_date := p_gift_date;
        ELSIF v_gift_status IS NOT NULL AND v_gift_status <> 'Delivered' THEN
            IF p_gift_date IS NOT NULL THEN
                RAISE_APPLICATION_ERROR(-20016, 'giftDate should not be passed when status is not Delivered.');
END IF;
            v_gift_date := NULL;
ELSE
            v_gift_date := NULL;
END IF;

UPDATE student SET
                   first_name   = p_first_name,
                   last_name    = p_last_name,
                   username     = p_username,
                   email        = p_email,
                   address_blob = v_address_blob,
                   gift_blob    = v_gift_blob,
                   gift_date    = v_gift_date,
                   updated_at   = SYSTIMESTAMP
WHERE student_id = p_student_id;

log_action(p_student_id, 'UPDATE', 'Student updated');
END;

    PROCEDURE get_student (
        p_student_id IN NUMBER,
        p_result     OUT SYS_REFCURSOR
    )
IS
BEGIN
OPEN p_result FOR
SELECT student_id,
       first_name,
       last_name,
       username,
       email,
       address_blob,
       gift_blob,
       gift_date,
       created_at,
       updated_at
FROM student
WHERE student_id = p_student_id;

log_action(p_student_id, 'READ', 'Student retrieved');
END;

    PROCEDURE delete_student (
        p_student_id IN NUMBER
    )
IS
BEGIN
DELETE FROM student
WHERE student_id = p_student_id;

log_action(p_student_id, 'DELETE', 'Student deleted');
END;

END student_pkg;
/



DECLARE
v_id NUMBER;
BEGIN
    -- 🎁 Student 1: Delivered Gift with giftDate
    student_pkg.create_student(
        p_first_name   => 'Ayaan',
        p_last_name    => 'Kumar',
        p_username     => 'ayaan.kumar',
        p_email        => 'ayaan.kumar@example.com',
        p_address_json => '{"street":"MG Road","city":"Bangalore","pin":"560001"}',
        p_gift_json    => '{"giftName":"Book","category":"Education","status":"Delivered"}',
        p_gift_date    => TO_TIMESTAMP('2025-07-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        p_student_id   => v_id
    );
    DBMS_OUTPUT.PUT_LINE('Inserted student Ayaan, ID: ' || v_id);

    -- 🎁 Student 2: Gift Pending (no giftDate)
    student_pkg.create_student(
        p_first_name   => 'Mira',
        p_last_name    => 'Patel',
        p_username     => 'mira.patel',
        p_email        => 'mira.patel@example.com',
        p_address_json => '{"street":"State St","city":"Chicago","pin":"60601"}',
        p_gift_json    => '{"giftName":"T-Shirt","category":"Apparel","status":"Pending"}',
        p_gift_date    => NULL,
        p_student_id   => v_id
    );
    DBMS_OUTPUT.PUT_LINE('Inserted student Mira, ID: ' || v_id);

    -- 🎁 Student 3: Gift Delivered with giftDate
    student_pkg.create_student(
        p_first_name   => 'Zaid',
        p_last_name    => 'Iqbal',
        p_username     => 'zaid.iqbal',
        p_email        => 'zaid.iqbal@example.com',
        p_address_json => '{"street":"Banjara Hills","city":"Hyderabad","pin":"500034"}',
        p_gift_json    => '{"giftName":"Pen","category":"Stationery","status":"Delivered"}',
        p_gift_date    => TO_TIMESTAMP('2025-07-03 16:30:00', 'YYYY-MM-DD HH24:MI:SS'),
        p_student_id   => v_id
    );
    DBMS_OUTPUT.PUT_LINE('Inserted student Zaid, ID: ' || v_id);

    -- 🎁 Student 4: No Gift Info
    student_pkg.create_student(
        p_first_name   => 'Reema',
        p_last_name    => 'Shah',
        p_username     => 'reema.shah',
        p_email        => 'reema.shah@example.com',
        p_address_json => '{"street":"Park Ave","city":"New York","pin":"10022"}',
        p_gift_json    => NULL,
        p_gift_date    => NULL,
        p_student_id   => v_id
    );
    DBMS_OUTPUT.PUT_LINE('Inserted student Reema, ID: ' || v_id);
END;
/

Select * from student;
