-- Step 1: Create Student Table
CREATE TABLE student (
                         student_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         first_name VARCHAR2(50),
                         last_name VARCHAR2(50),
                         username VARCHAR2(50),
                         email VARCHAR2(100),
                         address_blob BLOB,
                         created_at DATE DEFAULT SYSDATE,
                         updated_at DATE
);

-- Step 2: Create Package Specification
CREATE OR REPLACE PACKAGE student_pkg AS
    PROCEDURE create_student (
        p_first_name    IN VARCHAR2,
        p_last_name     IN VARCHAR2,
        p_username      IN VARCHAR2,
        p_email         IN VARCHAR2,
        p_address_json  IN CLOB,
        p_student_id    OUT NUMBER
    );

    PROCEDURE update_student (
        p_student_id    IN NUMBER,
        p_first_name    IN VARCHAR2,
        p_last_name     IN VARCHAR2,
        p_username      IN VARCHAR2,
        p_email         IN VARCHAR2,
        p_address_json  IN CLOB
    );

    PROCEDURE get_student (
        p_student_id IN NUMBER,
        p_student_cursor OUT SYS_REFCURSOR
    );

    PROCEDURE delete_student (
        p_student_id IN NUMBER
    );
END student_pkg;

-- Step 3: Create Package Body
CREATE OR REPLACE PACKAGE BODY student_pkg AS

    PROCEDURE create_student (
        p_first_name    IN VARCHAR2,
        p_last_name     IN VARCHAR2,
        p_username      IN VARCHAR2,
        p_email         IN VARCHAR2,
        p_address_json  IN CLOB,
        p_student_id    OUT NUMBER
    )
    IS
BEGIN
        IF p_first_name IS NULL OR TRIM(p_first_name) = '' THEN
            RAISE_APPLICATION_ERROR(-20001, 'First name is required.');
        ELSIF p_last_name IS NULL OR TRIM(p_last_name) = '' THEN
            RAISE_APPLICATION_ERROR(-20002, 'Last name is required.');
        ELSIF p_username IS NULL OR TRIM(p_username) = '' THEN
            RAISE_APPLICATION_ERROR(-20003, 'Username is required.');
        ELSIF p_email IS NULL OR TRIM(p_email) = '' THEN
            RAISE_APPLICATION_ERROR(-20004, 'Email is required.');
END IF;

INSERT INTO student (
    first_name, last_name, username, email,
    address_blob, created_at
)
VALUES (
           p_first_name, p_last_name, p_username, p_email,
           UTL_RAW.CAST_TO_RAW(SUBSTR(p_address_json, 1, 4000)),
           SYSDATE
       )
    RETURNING student_id INTO p_student_id;
END create_student;

    PROCEDURE update_student (
        p_student_id    IN NUMBER,
        p_first_name    IN VARCHAR2,
        p_last_name     IN VARCHAR2,
        p_username      IN VARCHAR2,
        p_email         IN VARCHAR2,
        p_address_json  IN CLOB
    )
IS
BEGIN
        IF p_student_id IS NULL THEN
            RAISE_APPLICATION_ERROR(-20010, 'Student ID is required for update.');
        ELSIF p_first_name IS NULL OR TRIM(p_first_name) = '' THEN
            RAISE_APPLICATION_ERROR(-20011, 'First name is required for update.');
        ELSIF p_last_name IS NULL OR TRIM(p_last_name) = '' THEN
            RAISE_APPLICATION_ERROR(-20012, 'Last name is required for update.');
        ELSIF p_username IS NULL OR TRIM(p_username) = '' THEN
            RAISE_APPLICATION_ERROR(-20013, 'Username is required for update.');
        ELSIF p_email IS NULL OR TRIM(p_email) = '' THEN
            RAISE_APPLICATION_ERROR(-20014, 'Email is required for update.');
END IF;

UPDATE student
SET first_name   = p_first_name,
    last_name    = p_last_name,
    username     = p_username,
    email        = p_email,
    address_blob = UTL_RAW.CAST_TO_RAW(SUBSTR(p_address_json, 1, 4000)),
    updated_at   = SYSDATE
WHERE student_id = p_student_id;
END update_student;

    PROCEDURE get_student (
        p_student_id IN NUMBER,
        p_student_cursor OUT SYS_REFCURSOR
    )
IS
BEGIN
OPEN p_student_cursor FOR
SELECT * FROM student WHERE student_id = p_student_id;
END get_student;

    PROCEDURE delete_student (
        p_student_id IN NUMBER
    )
IS
BEGIN
DELETE FROM student WHERE student_id = p_student_id;
END delete_student;

END student_pkg;

-- Step 4: Insert Sample Data Using Stored Procedure
DECLARE
v_student_id NUMBER;
    v_address CLOB := '{"Address":{"city":"providence","state":"RI","zipcode":"02908"}}';
BEGIN
    student_pkg.create_student(
        p_first_name    => 'Kabir',
        p_last_name     => 'Gautam',
        p_username      => 'kabir.g',
        p_email         => 'kabir@example.com',
        p_address_json  => v_address,
        p_student_id    => v_student_id
    );

    DBMS_OUTPUT.PUT_LINE('Student created with ID: ' || v_student_id);
END;
